### ISSUE TITLE
Why log_prevterm = 1000000?

### ISSUE THREAD

**Issue by vidhiJain** [abhishekgupta-1/FUCloud#5]
https://github.com/abhishekgupta-1/FUCloud/blob/2d36fe6f780a234158eafeadf379d7f263ff1a14/server.py#L221

**Comment by vidhiJain** [comment]
Possible error will occur here

https://github.com/abhishekgupta-1/FUCloud/blob/2d36fe6f780a234158eafeadf379d7f263ff1a14/server.py#L225

**Comment by abhishekgupta-1** [comment]
The statement  log_prevTerm = 10000000 #Possibly faulty!  was not required. Hence removed!
